### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Martifan** [Yoonit-Labs/android-yoonit-facefy#17] opened 2021-12-05 00:05 UTC
Hello everyone, when I try to compile the project, it gives me an error:
`Could not find com.github.Yoonit-Labs:android-yoonit-facefy:master-SNAPSHOT.`

who knows how to fix it?

thank you in advance

**Comment by TeruyaHaroldo** [comment] 2021-12-06 12:44
Hi @Martifan.
The project is trying to find the branch `Master` from the `android-yoonit-facefy`. Probably it is not updated.

First try to update OR
Try to:
1. In the `build.gradle` change the dependency path to `com.github.Yoonit-Labs:android-yoonit-facefy:1.0.5` (latest);
2. Clean project
3. Run

Please, let me know if it not worked for you.

**Comment by Martifan** [comment] 2021-12-07 00:21
Could not find com.github.Yoonit-Labs:android-yoonit-facefy:1.0.5.
Required by:
    project :app
Search in build.gradle files

**Comment by Martifan** [comment] 2021-12-16 09:35
UP

**Comment by Martifan** [comment] 2021-12-18 23:18
hello do you have any news?

**Comment by luiguild** [comment] 2021-12-19 07:45
Hello @Martifan.

It has no secret, this is the git that you are trying to use, here you can find the tag '1.0.5', check your syntax related with the path and check if you can reach some content using git through jitpack, here you can find more information and the fully jitpack documentation.

Also, I tried here and it's worked fine. It's not a bug and we can't do anything to solve. You are still welcome to keep commenting but I'll close this issue by now. Let us know, please.

https://jitpack.io/#yoonit-labs/android-yoonit-facefy/1.0.5

Good luck!

**Closed as completed by luiguild** 2021-12-19 07:45 UTC
